# Site settings
title: Daniel Morales
email: dnlmrls9@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Daniel Morales a passionate Software Engineer with manifold interests in the field of Data and Software Engineer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://danielmorales9.github.io" # the base hostname & protocol for your site
github_username:  DanielMorales9

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
